apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petri.fullname" . }}
  labels:
    {{- include "petri.labels" . | nindent 4 }}
{{- $root := . }}
spec:
  {{- if not $root.Values.autoscaling.enabled }}
  replicas: {{ $root.Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "petri.selectorLabels" $root | nindent 6 }}
  template:
    {{- $podAnnotations := dict "checksum/config" (include (print $root.Template.BasePath "/configmap.yaml") $root | sha256sum) }}
    {{- if $root.Values.metrics.podAnnotations.enabled }}
    {{- $_ := set $podAnnotations "prometheus.io/scrape" "true" }}
    {{- $_ := set $podAnnotations "prometheus.io/path" $root.Values.metrics.path }}
    {{- $_ := set $podAnnotations "prometheus.io/port" (printf "%v" $root.Values.service.port) }}
    {{- end }}
    {{- range $key, $value := $root.Values.podAnnotations }}
    {{- $_ := set $podAnnotations $key (printf "%v" $value) }}
    {{- end }}
    metadata:
      annotations:
        {{- toYaml $podAnnotations | nindent 8 }}
      labels:
        {{- include "petri.selectorLabels" $root | nindent 8 }}
    spec:
      {{- with $root.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml $root.Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ $root.Chart.Name }}
          securityContext:
            {{- toYaml $root.Values.securityContext | nindent 12 }}
          image: "{{ $root.Values.image.registry }}/{{ $root.Values.image.repository }}:{{ $root.Values.image.tag | default $root.Chart.AppVersion }}"
          imagePullPolicy: {{ $root.Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          {{- if $root.Values.startupProbe.enabled }}
          startupProbe:
            {{- toYaml (omit $root.Values.startupProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if $root.Values.livenessProbe.enabled }}
          livenessProbe:
            {{- toYaml (omit $root.Values.livenessProbe "enabled") | nindent 12 }}
          {{- end }}
          {{- if $root.Values.readinessProbe.enabled }}
          readinessProbe:
            {{- toYaml (omit $root.Values.readinessProbe "enabled") | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml $root.Values.resources | nindent 12 }}
          env:
            {{- range $key, $value := $root.Values.env }}
            {{- if and $value (not (index $root.Values.secrets $key)) }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            {{- range $key, $secret := $root.Values.secrets }}
            {{- if $secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  name: {{ include "petri.fullname" $root }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "petri.fullname" $root }}
          {{- if $root.Values.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: {{ $root.Values.persistence.mountPath }}
          {{- end }}
      {{- if $root.Values.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "petri.fullname" $root }}
      {{- end }}
      {{- with $root.Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $root.Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
