-- The state machine.
--
-- Portable across H2 and PostgreSQL: identity columns rather than SERIAL,
-- TIMESTAMP WITH TIME ZONE rather than a bare TIMESTAMP, and unbounded VARCHAR
-- for free text (Postgres has no CLOB, H2 no TEXT alias worth relying on).

CREATE TABLE board (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug           VARCHAR(64)  NOT NULL,
    name           VARCHAR(255) NOT NULL,
    forge          VARCHAR(32)  NOT NULL,
    repository     VARCHAR(255) NOT NULL,
    default_branch VARCHAR(255) NOT NULL,
    enabled        BOOLEAN      NOT NULL,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uk_board_slug UNIQUE (slug)
);

-- One row per column on the board. This is the whole point of Petri: which
-- model drains which state, what checks its output, and where the card goes
-- next are configuration rows, not code.
--
-- next_on_pass / next_on_fail are nullable self-references so a pipeline can be
-- inserted in any order and linked afterwards; a terminal state leaves both null.
CREATE TABLE workflow_state (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id        BIGINT      NOT NULL,
    name            VARCHAR(64) NOT NULL,
    position        INTEGER     NOT NULL,
    terminal        BOOLEAN     NOT NULL,
    model_alias     VARCHAR(128),
    prompt_template VARCHAR,
    gate            VARCHAR(32) NOT NULL,
    next_on_pass    BIGINT,
    next_on_fail    BIGINT,
    max_attempts    INTEGER     NOT NULL,
    CONSTRAINT uk_state_board_name UNIQUE (board_id, name),
    CONSTRAINT fk_state_board     FOREIGN KEY (board_id)     REFERENCES board (id),
    CONSTRAINT fk_state_pass      FOREIGN KEY (next_on_pass) REFERENCES workflow_state (id),
    CONSTRAINT fk_state_fail      FOREIGN KEY (next_on_fail) REFERENCES workflow_state (id)
);

CREATE TABLE card (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id         BIGINT       NOT NULL,
    state_id         BIGINT       NOT NULL,
    title            VARCHAR(512) NOT NULL,
    description      VARCHAR,
    branch           VARCHAR(255),
    pull_request_url VARCHAR(1024),
    attempts         INTEGER      NOT NULL,
    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_card_board FOREIGN KEY (board_id) REFERENCES board (id),
    CONSTRAINT fk_card_state FOREIGN KEY (state_id) REFERENCES workflow_state (id)
);

-- One execution of one state's action against one card.
--
-- last_event_at is not decoration. A session reports "busy" for the whole of a
-- single model call, which can legitimately run for minutes, so status alone
-- cannot distinguish working from hung. Status plus time-since-last-event can.
CREATE TABLE agent_run (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id       BIGINT      NOT NULL,
    state_id      BIGINT      NOT NULL,
    attempt       INTEGER     NOT NULL,
    session_id    VARCHAR(128),
    status        VARCHAR(32) NOT NULL,
    started_at    TIMESTAMP WITH TIME ZONE,
    last_event_at TIMESTAMP WITH TIME ZONE,
    finished_at   TIMESTAMP WITH TIME ZONE,
    exit_code     INTEGER,
    summary       VARCHAR,
    CONSTRAINT fk_run_card  FOREIGN KEY (card_id)  REFERENCES card (id),
    CONSTRAINT fk_run_state FOREIGN KEY (state_id) REFERENCES workflow_state (id)
);

-- Append-only history. "in_progress" says nothing; this says which model moved
-- a card, on which attempt, past which gate, and what the verdict was.
CREATE TABLE transition (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_id       BIGINT       NOT NULL,
    from_state_id BIGINT,
    to_state_id   BIGINT       NOT NULL,
    run_id        BIGINT,
    actor         VARCHAR(128) NOT NULL,
    verdict       VARCHAR,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_transition_card FOREIGN KEY (card_id)       REFERENCES card (id),
    CONSTRAINT fk_transition_from FOREIGN KEY (from_state_id) REFERENCES workflow_state (id),
    CONSTRAINT fk_transition_to   FOREIGN KEY (to_state_id)   REFERENCES workflow_state (id),
    CONSTRAINT fk_transition_run  FOREIGN KEY (run_id)        REFERENCES agent_run (id)
);

CREATE INDEX idx_card_state       ON card (state_id);
CREATE INDEX idx_card_board       ON card (board_id);
CREATE INDEX idx_run_card         ON agent_run (card_id);
CREATE INDEX idx_run_status       ON agent_run (status);
CREATE INDEX idx_transition_card  ON transition (card_id);
